ccflags-y += -Idrivers/media/platform/msm/camera_v2_v4xx
ccflags-y += -Idrivers/media/platform/msm/camera_v2_v4xx/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_v4xx/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
