ccflags-y += -Idrivers/media/platform/msm/camera_v2_v4xx
ccflags-y += -Idrivers/media/platform/msm/camera_v2_v4xx/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_v4xx/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
